### ISSUE TITLE
Missing "Facade" suffix

### ISSUE THREAD

**Issue by innoflash** [bitfumes/laravel-packer#16]
https://github.com/bitfumes/laravel-packer/blob/5d89c9063fd903bcaee96d203d65241a3c98a1d5/app/Commands/Standalone/stubs/ServiceProvider.stub#L59

When you create a package say ```flash-package``` the ```register``` on facade in the ServiceProvider registers the class ```FlashPackage``` instead of ```FlashPackageFacade```

**Comment by sarthaksavvy** [comment]
Thanks, I will check that and correct in next release
