### ISSUE TITLE
Creating migrations uses wrong path for file

### ISSUE THREAD

**Issue by ThaDaVos** [bitfumes/laravel-packer#48]
When creating a migration it fails as it tries to write it to my composer global directory, any idea why?
Adding `--path="${PWD}/database/migrations" --realpath` each time I want to create a migration is a little cumbersome
![image](https://user-images.githubusercontent.com/5251028/126142543-b0b4f6d0-3010-4ce2-9188-4d82c51fdab7.png)

**Comment by sarthaksavvy** [comment]
fixed, please run 'composer global update' to get latest version

**Comment by ThaDaVos** [comment]
Where are they written to now?

Not inside the package at least...

**Comment by ThaDaVos** [comment]
I found what goes wrong, just don't know why - it tries to resolve the path to my package but it does the following
`/home/projects/{some_project}/vendor/{some_vendor}/{package_name}` is my package folder
It generates the following path for my migrations:
`/home/projects/{some_project}/vendor/{some_vendor}/{package_name}database/migrations`
While it should be:
`/home/projects/{some_project}/vendor/{some_vendor}/{package_name}/database/migrations`

As you can see, the `/` is missing for some reason

**Comment by ThaDaVos** [comment]
I think it's this line:
https://github.com/bitfumes/laravel-packer/blob/master/app/Commands/Foundation/Migrations/MigrationCreator.php#L31

`getcwd()` doesn't return a trailing `/`, so the building blocks will be:
`getcwd()="/home/projects/{some_project}/vendor/{some_vendor}/{package_name}"`
`$devPath=""`
`database/migrations`

This results in `"/home/projects/{some_project}/vendor/{some_vendor}/{package_name}" . "" . "database/migrations"`
Which results in:
`/home/projects/{some_project}/vendor/{some_vendor}/{package_name}database/migrations`

This went unnoticed probably as `$devPath` always has a trailing `/`

Maybe set the default of `$devPath` to `"/"` instead of `""`?

**Comment by ThaDaVos** [comment]
Also the `path` and `realpath` options seem to be broken or not used anymore... workaround mentioned in first message doesn't work anymore - as it keeps writing them to the wrong path
