### ISSUE TITLE
packer make:migrations not working

### ISSUE THREAD

**Issue by uriahg17** [bitfumes/laravel-packer#6]
Im getting this error when running packer make:migrations
```
In Filesystem.php line 442:
                                      
  mkdir(): No such file or directory  
                                      
```

**Comment by morpheus7CS** [comment]
Hey,

you have a typo in the command. Correct is `packer make:migration`.

**Comment by clevonnoel** [comment]
I am experiencing the same issue

**Comment by morpheus7CS** [comment]
Hey @clevonnoel,

can you post a screenshot of the console output below? Thanks!

**Comment by clevonnoel** [comment]
See attached:

![image](https://user-images.githubusercontent.com/928639/49457761-c8897300-f7c1-11e8-9b80-f92e588cf391.png)

**Comment by sarthaksavvy** [comment]
Hey, thanks for raising this issue.
Let me check and fir it.

**Comment by sarthaksavvy** [comment]
Hey, fixed.
Update your global composer packages and problem will be fixed.
